### ISSUE TITLE
How can convert to ncnn param and bin files

### ISSUE THREAD

**Issue by GongmingHu** [CVHub520/yolov5_obb#1]
hello, thanks for your great work! I convert the onnx file to ncnn format,  i get the unsupported slice step, how can i to fix it?
![微信图片_20231106201409](https://github.com/CVHub520/yolov5_obb/assets/49218815/4c55c096-f5d4-41e7-9f9e-1caa21020d7b)

**Comment by CVHub520** [comment]
Hello, @GongmingHu and thank you for your kind words! It appears that you are trying to convert an ONNX file to the NCNN format, and you're encountering an `unsupported slice step` issue. This issue may be related to using an older version of yolov5_obb, which is based on YOLOv5 v5.0 and contains the Focus module. 

Regarding NCNN support, I haven't delved into it extensively, but based on the error message, it seems that the inference framework you are using might not yet support this specific operator. Here are a few potential suggestions:

1. Try removing the layer causing the error and replace it with a custom layer as a workaround. Make sure to adjust the output parameters accordingly.
2. You can manually modify the ncnn.param file to perform operator replacements. You may need to search for relevant resources on how to do this.
3. I strongly recommend considering migrating to this [project](https://github.com/CVHub520/yolov5_obb) for training and exporting, as it may provide a more comprehensive solution.

If you have any more questions or need further guidance, please feel free to ask.

Best regards,
CVHub

**Comment by GongmingHu** [comment]
@CVHub520 Hello, thanks for your advice!! I have solved the problem by adding command --train when exporting .pth weight to onnx format.

**Comment by GongmingHu** [comment]
> Hello, @GongmingHu and thank you for your kind words! It appears that you are trying to convert an ONNX file to the NCNN format, and you're encountering an `unsupported slice step` issue. This issue may be related to using an older version of yolov5_obb, which is based on YOLOv5 v5.0 and contains the Focus module.
> 
> Regarding NCNN support, I haven't delved into it extensively, but based on the error message, it seems that the inference framework you are using might not yet support this specific operator. Here are a few potential suggestions:
> 
> 1. Try removing the layer causing the error and replace it with a custom layer as a workaround. Make sure to adjust the output parameters accordingly.
> 2. You can manually modify the ncnn.param file to perform operator replacements. You may need to search for relevant resources on how to do this.
> 3. I strongly recommend considering migrating to this [project](https://github.com/CVHub520/yolov5_obb) for training and exporting, as it may provide a more comprehensive solution.
> 
> If you have any more questions or need further guidance, please feel free to ask.
> Hello, thanks for your advice!! I have solved the problem by adding command --train when exporting .pth weight to onnx format.
> Best regards, CVHub

**Comment by GongmingHu** [comment]
@CVHub520 
Hello, thanks for your advice! !!! I have resolved the problem by adding command --train when exporting the .pth weight to onnx file.

**Comment by CVHub520** [comment]
That sounds great! Thanks for sharing your valuable feedback!
